# handle the following error and print the message

[1, 2, 3].first('two')
